### ISSUE TITLE
ScopedAttributeELResolver.setValue() does not check if view is transient before calling getViewMap()

### ISSUE THREAD

**Issue by javaserverfaces** [javaee/mojarra#3943]
com.sun.faces.el.ScopedAttributeELResolver.setValue() does not check if view root is transient before calling getViewMap(). This causes warnings like '@ViewScoped beans are not supported on stateless views'.
#### Affected Versions
[2.3.0-m02]

**Comment by kalgon** [comment]
Could this be re-examined please? The bug is still present in the current version.

`ScopedAttributeELResolver` should always call `getViewMap(false)`/`getSessionMap(false)` (instead of `getViewMap()`/`getSessionMap()`) in `setValue()` and `getValue()` so that it won't inadvertently create a view/session scope.
